# This playbook will install Redis, RabbitMQ, and the
# Sensu API and Sensu Server components in Docker conatiners
# on the Director/undercloud node.
---
- name: Install prerequisites on all hosts and gather facts
  hosts: undercloud
  tags:
    - prereqs
  roles:
    - firewall/gather
    - prereqs
    - repos
    - chrony

- name: Install Redis
  hosts: undercloud
  tags:
    - availability
    - redis
  roles:
    - redis/server-docker

- name: Install RabbitMQ
  hosts: undercloud
  tags:
    - availability
    - rabbitmq
  roles:
    - rabbitmq/server-docker

- name: Install Sensu
  hosts: undercloud
  tags:
    - availability
    - sensu
  roles:
    - sensu/server-docker
    - sensu/client
