---
- name: Install rdo repository configuration
  package:
    name: centos-release-openstack-{{rdo_release}}
    state: present
  when: manage_repos|default(false) and ansible_distribution == 'CentOS'

# workaround for centos-qemu-ev and centos-release issue
#
- name: update centos-release rpm
  yum:
    name: centos-release
    state: latest
    disablerepo: centos-qemu-ev
  when: manage_repos|default(false) and ansible_distribution == 'CentOS'
  tags:
    - skip_ansible_lint
