---
# Sensu package name.
sensu_package_name: sensu

# Sensu server service name.
sensu_server_service_name: sensu-server

# Sensu API service name.
sensu_api_service_name: sensu-api

# Sensu client service name.
sensu_client_service_name: sensu-client

# Path to Sensu configuration directory.
sensu_config_path: /etc/sensu/conf.d

# Path to Sensu plugin directory
sensu_plugin_path: /etc/sensu/plugins

# Path to Sensu log directory.
sensu_log_path: /var/log/sensu

# Path to Sensu runtime directory.
sensu_runtime_path: /var/run/sensu

# Owner of Sensu configuration files.
sensu_owner: sensu

# Group of Sensu configuration files.
sensu_group: sensu

# Address of RabbitMQ server to which Sensu should connect.
sensu_rabbitmq_server: localhost

# Port of the RabbitMQ server.
sensu_rabbitmq_port: 5672

# Port of the RabbitMQ server for SSL communication.
sensu_rabbitmq_ssl_port: 5671

# Authenticate to RabbitMQ server as this user.
sensu_rabbitmq_user: sensu

# Authenticate to RabbitMQ server with this password.
sensu_rabbitmq_password: sensu

# RabbitMQ vhost for use by Sensu.
sensu_rabbitmq_vhost: /sensu

sensu_minimum_version: "1:0.26.0"

# Address on which Sensu should listen for connections.
sensu_api_bind: 0.0.0.0

# Port on which Sensu API should listen.
sensu_api_port: 4567

# Address to which clients should connect to contact the Sensu API.
sensu_api_server: localhost

# Whether or not to enable authentication on sensu-api
sensu_api_authentication: false

# If sensu-api authentication is enabled, the username
sensu_api_username: sensu

# If sensu-api-authentication is enabled, the password
sensu_api_password: sensu

# Address of the Redis server to which Sensu should connect.
sensu_redis_server: 127.0.0.1

# Port on which the Redis server listens.
redis_listen_port: "{{ '6379' if sensu_docker is undefined else '16379' }}"

# Password for authenticating to Redis.
sensu_redis_password: "{{ redis_password }}"

# Subscription string for monitoring host
sensu_client_subscription: 'monitoring-node'

# Address on which Sensu client should listen on monitoring host.
sensu_client_bind: 127.0.0.1

# Port on which Sensu client should listen on monitoring host.
sensu_client_port: 3030

# Name for client service displayed in Uchiwa
sensu_client_name: '{{ ansible_fqdn }}'

# Address for client service displayed in Uchiwa
sensu_client_address: '{{ ansible_default_ipv4.address }}'

# Whether oschecks and default checks should be installed
sensu_manage_checks: true

oschecks_package_name: osops-tools-monitoring-oschecks

# A list of Sensu checks that will run on the overcloud hosts. The
# only required key for each item is `name`. The systemd `service`
# used in `systemctl` checks defaults to `openstack-<name>`, and the
# `subscribers` key defaults to `[ "overcloud-<name>" ]`.
#
# The following checks are disabled because the corresponding services
# are run as WSGI applications under Apache.  This means that we don't
# have a good client-side healthcheck until we make changes either to
# sensu packaging or our tripleo integration.
#
# .. code-block:: yaml
#
#     - name: ceilometer-api
#     - name: keystone-api
#       subscribers:
#         - overcloud-keystone
#         - overcloud-kestone
#     - name: aodh-api
#       subscribers:
#         - overcloud-ceilometer-aodh-api
#
sensu_overcloud_checks:
  - name: cinder-scheduler
  - name: neutron-api
    service: neutron-server
  - name: neutron-dhcp-agent
    service: neutron-dhcp-agent
  - name: neutron-l3-agent
    service: neutron-l3-agent
  - name: neutron-metadata-agent
    service: neutron-metadata-agent
    subscribers:
      - overcloud-neutron-metadata
  - name: neutron-ovs-agent
    service: neutron-openvswitch-agent
  - name: nova-libvirt
    service: libvirtd
  - name: pacemaker
    service: pacemaker

# A list of sensu checks for service managed as resources in pacemaker
sensu_overcloud_checks_pcs:
  - name: rabbitmq-bundle
    subscribers:
      - overcloud-rabbitmq
  - name: galera-bundle
    subscribers:
      - overcloud-galera
  - name: redis-bundle
    subscribers:
      - overcloud-redis
  - name: haproxy-bundle
    subscribers:
      - overcloud-haproxy
  - name: openstack-cinder-volume
    subscribers:
      - overcloud-cinder-volume

# A list of sensu checks that will run on an opstools server
sensu_remote_checks: []

# Username for openstack checks.
oscheck_default_username: admin

# Password for openstack checks.
oscheck_default_password: pass

# Project name (aka tenant) for openstack checks.
oscheck_default_project_name: admin

# Authentication URL (Keystone server) for openstack checks.
oscheck_default_auth_url: http://controller:5000/v2.0

# Region name for openstack checks.
oscheck_default_region_name: RegionOne

# Whether to group HAProxy stats by service instead of by host
haproxycheck_by_sevice: false
